class PalabraDia {

    static palabraSecreta = null;

    static seleccionarPalabra() {
        const indice = Math.floor(Math.random() * this.palabras.length);
        this.palabraSecreta = this.palabras[indice];
        console.log("Palabra del día seleccionada:", this.palabraSecreta);
        return this.palabraSecreta;
    }

    static getPalabraDelDia() {
        if (!this.palabraSecreta) {
            this.seleccionarPalabra();
        }

        return this.palabraSecreta;
    }

    static reiniciarPalabra() {
        this.palabraSecreta = null;
    }

    static palabras = [
        "CASA",
        "NUBE",
        "RIO",
        "PAPEL",
        "SILLA",
        "CAMINO",
        "VENTANA",
        "BOSQUE",
        "RELOJ",
        "PUERTA",
        "ARENA",
        "FUEGO",
        "NARANJA",
        "PERRO",
        "GATO",
        "MESA",
        "SOMBRERO",
        "MONTANA",
        "ZAPATO",
        "CUADRO",
        "ESPEJO",
        "TIJERA",
        "CUERDA",
        "BARCO",
        "LLAVE",
        "PLUMA",
        "JARDIN",
        "TREN",
        "PIEDRA",
        "HARINA",
        "CUCHARA",
        "TEJADO",
        "HORMIGA",
        "BOTELLA",
        "LINTERNA",
        "PELOTA",
        "COLINA",
        "CHARCO",
        "MANTEL",
        "CAJON",
        "GRILLO",
        "CAMISA",
        "BUFANDA",
        "PINTURA",
        "ALMOHADA",
        "PALMERA",
        "CASCADA",
        "CUADERNO",
        "BURBUJA",
        "MARTILLO",
        "ESCALERA",
        "TRUENO",
        "FAROL",
        "MALETA",
        "CARRETA",
        "MANZANA",
        "HELADO",
        "NIDO",
        "RATON",
        "CASTILLO",
        "ABISMO",
        "MADERA",
        "GUITARRA",
        "SOMBRA",
        "CANDADO",
        "LAGUNA",
        "PAJARO",
        "SEMILLA",
        "CEREZA",
        "MOLINILLO",
        "ZAPATERIA",
        "ALFOMBRA",
        "CINTURON",
        "FOGATA",
        "PALACIO",
        "BIGOTE",
        "ESTANQUE",
        "MOCHILA",
        "MEDALLA",
        "CANGREJO",
        "TOMATE",
        "AVION",
        "CAMPANA",
        "VIOLIN",
        "PIRATA",
        "CARACOL",
        "PANAL",
        "ESPUMA",
        "LADRILLO",
        "CAMELLO",
        "CABANA",
        "BASTON",
        "VOLCAN",
        "COLLAR",
        "CARPETA",
        "ABANICO",
        "COJIN",
        "GLOBO",
        "PARQUE",
        "CERRO",
        "GAFAS",
        "CAJA",
        "FARO",
        "DEDAL",
        "RUEDA",
        "BUZON",
        "ANCLA",
        "PEPINO",
        "TRONCO",
        "CACTUS",
        "ESPONJA",
        "MORRAL",
        "PINCEL",
        "CANASTA",
        "GRANJA",
        "SARTEN",
        "PERCHA",
        "HIELO",
        "NIEBLA",
        "CORBATA",
        "PALOMA",
        "REMOLINO",
        "COBRE",
        "MAPA",
        "CANELA",
        "PUPITRE",
        "LAGARTO",
        "TROMPETA",
        "CENTELLA",
        "BODEGA",
        "TAPIZ",
        "BALANZA",
        "JINETE",
        "COLMILLO",
        "TINTERO",
        "PASTEL",
        "PUNAL",
        "MURALLA",
        "ALFILER",
        "CANARIO",
        "ESTUFA",
        "PANDERO",
        "ORILLA",
        "MIMBRE",
        "COFRE",
        "PASILLO",
        "CUENCO",
        "RAMA",
        "HOGUERA",
        "TESORO",
        "BARRIL",
        "ZORRO",
        "CISNE",
        "COMETA",
        "SELLO",
        "TABURETE",
        "GUANTE",
        "MOLINO",
        "CUBO",
        "SENDERO",
        "HIEDRA",
        "RUBI",
        "BRONCE"
    ];
}
